version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"

  web:
    build:
      context: .
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_KEY: $API_KEY
      CSE_ID: $CSE_ID

    command: /bin/sh -c "rm -f tmp/pids/server.pid && \bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/$WORKDIR"
    depends_on:
      - db
    ports:
      - "$WEB_PORT:3000"
